language: node_js # node环境
os: linux
dist: xenial
node_js:
  - lts/*
script:
  - npm run docs:build # 执行命令
deploy:
  commit_message: ":construction_worker:Deploy %{project_name} with Travis CI ROBOT"
  strategy: git
  provider: pages
  cleanup: true
  local_dir: docs/.vuepress/dist # 部署的文件夹文件
  token: ${GH_TOKEN} # travis服务上的token变量
  target_branch: gh-pages # 集成发布到gh-pages上
  keep_history: true
  on:
    branch: main